install:
  - nuget restore ./Source/Funky.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory nunit-runner
language: csharp
script:
  - xbuild /p:Configuration=Release ./Source/Funky.sln
  - mono ./nunit-runner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Funky.UnitTests/bin/Release/Funky.UnitTests.dll
solution: ./Source/Funky.sln